name: disfruta_antofagasta  
description: "Museo RapaNui - Isla de Pascua"
publish_to: 'none'

# Nueva versiÃ³n para App Store
version: 1.0.9+5

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  intl: ^0.20.2
  dio: ^5.9.0
  connectivity_plus: ^6.1.5
  google_fonts: ^6.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  pdfx: ^2.9.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  easy_localization: ^3.0.8
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  formz: ^0.8.0
  animations: ^2.1.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.39
  shared_preferences: ^2.2.2

  # ðŸ‘‰ plugin local de QR
  qr_code_scanner:
    path: packages/qr_code_scanner

  # Renderizado de HTML
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env

    # Weather
    - assets/weather/

    # ImÃ¡genes generales
    - assets/logo.png
    - assets/logo_museo.png
    - assets/icon_ios.png
    - assets/bg_portada.png
    - assets/icons/

    # PDFs
    - assets/pdf/antofagasta-mapa-turistico-mobile-small.pdf

    # ðŸŒ TRADUCCIONES (CLAVE)
    - assets/i18n/

# ===========================================
# ðŸ”¥ ICONOS
# ===========================================
flutter_launcher_icons:
  android: true
  ios: false

  image_path_android: "assets/icons/mapse_launcher.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/icons/mapse_launcher.png"
  min_sdk_android: 21

# ===========================================
# ðŸ”¥ SPLASH SCREEN
# ===========================================
flutter_native_splash:
  color: "#000000"
  image: assets/icons/mapse_launcher.png
  android: false
  ios: true
