name: disfruta_antofagasta
description: "Museo RapaNui - Isla de Pascua"
publish_to: 'none'

version: 1.2.3+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  intl: ^0.20.2
  dio: ^5.9.0
  connectivity_plus: ^6.1.5
  google_fonts: ^6.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2

  photo_view: ^0.15.0

  pdfx: ^2.9.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  easy_localization: ^3.0.8
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  formz: ^0.8.0
  animations: ^2.1.0

  # Audio base
  audioplayers: ^6.1.0
  just_audio: ^0.9.39

  # ✅ Notificación Android + LockScreen/ControlCenter iOS
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  rxdart: ^0.27.7
  permission_handler: ^11.3.1

  shared_preferences: ^2.2.3

  qr_code_scanner:
    path: packages/qr_code_scanner

  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/weather/
    - assets/logo.png
    - assets/logo_museo.png
    - assets/icon_ios.png
    - assets/bg_portada.png
    - assets/icons/
    - assets/splash/android12_icon.png
    - assets/flags/
    - assets/pdf/antofagasta-mapa-turistico-mobile-small.pdf
    - assets/i18n/
    - assets/data/countries_fallback.json

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: "assets/icons/mapse_launcher.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/icons/mapse_launcher.png"
  min_sdk_android: 21

  image_path_ios: "assets/icon_ios.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  android: true
  ios: true

  android_12:
    color: "#000000"
    image: assets/splash/android12_icon.png
